# Generated by Django 4.2.7 on 2023-12-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_result_csvfile_alter_result_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(blank=True, null=True, upload_to='SubmittedCSV')),
            ],
        ),
    ]
