# Generated by Django 4.2.7 on 2023-12-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_usercsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercsv',
            name='csv',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
