# Generated by Django 4.2.7 on 2023-12-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_result_csvfile_alter_result_plot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvName', models.TextField()),
            ],
        ),
    ]
