# Generated by Django 4.2.7 on 2023-12-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_csvnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercsv',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
