# Generated by Django 4.2.7 on 2023-12-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_usercsv_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvnames',
            name='csvName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
